import MobileNav from "@/components/sideBar/MobileNav";
import SideBar from "@/components/sideBar/SideBar";

export const dynamic = "force-dynamic";


export const metadata = {
  title: "BookMark / Y",
  description: "Generated by create next app"
};

export default async  function BookmarkLayout({ children }) {
  
  return (
    <section className="grid grid-cols-12 max-w-6xl mx-auto">
      <SideBar />
      <div className="col-span-7 max-md:col-span-11 max-sm:col-span-12  border-r">
        {children}
        <MobileNav />
      </div>
    </section>
  );
}
