import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ui/theme-provider";
import ReactQueryProvider from "./provider/ReactQueryProvider";
import ThemeDataProvider from "./provider/ThemeDataProvider";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const clerkFrontendApi = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ClerkProvider frontendApi={clerkFrontendApi}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <ThemeDataProvider>
              <ReactQueryProvider>
                {children}
                <Toaster />                
              </ReactQueryProvider>
            </ThemeDataProvider>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
